# Site Settings
title: "Joel A. Van Fossen"
name: "Joel A. Van Fossen"
description: "Assistant Professor of Philosophy"
url: "https://joelvanfossen.github.io"
baseurl: ""
repository: "joelvanfossen/joelvanfossen.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Author Profile (Sidebar)
author:
  name: "Joel A. Van Fossen"
  avatar: "/images/HUD_277.jpg"
  bio: "Assistant Professor of Philosophy"
  location: ""
  links:
    - label: "Research Map"
      icon: "fas fa-fw fa-link"
      url: "https://researchmap.jp/joelavanfossen"
    - label: "Phil People"
      icon: "fas fa-fw fa-users"
      url: "https://philpeople.org/profiles/joel-a-van-fossen"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-1718-7003"

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Minimal Mistakes Specifics
locale: "en-US"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joelvanfossen"
