# Site Settings
title: "Joel A. Van Fossen"
name: "Joel A. Van Fossen"
description: "Assistant Professor of Philosophy"
url: "https://joelavanfossen.github.io"
baseurl: "" 
repository: "joelavanfossen/joelavanfossen.github.io"
remote_theme: "academicpages/academicpages.github.io"

# Author Profile (Sidebar)
author:
  name: "Joel A. Van Fossen"
  avatar: "/images/HUD_277.jpg"
  bio: "Assistant Professor of Philosophy"
  location: "Kawasaki, Japan"
  links:
    - label: "Research Map"
      icon: "fas fa-fw fa-link"
      url: "https://researchmap.jp/joelavanfossen"
    - label: "Phil People"
      icon: "fas fa-fw fa-users"
      url: "https://philpeople.org/profiles/joel-a-van-fossen"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-1718-7003"

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Specific AcademicPages Settings
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rantfile", "mkmf.log", "setup.php", "LICENSE.txt", "README.md"]
